### ISSUE TITLE
DBT Test Not Dropping/Overwriting Test Tables Prior to Subsequent Executions

### ISSUE THREAD

**Issue by DEVi1wing** [Teradata/dbt-teradata#34] opened 2022-03-18 15:38 UTC
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?

DBT-Teradata is not replacing prior results when running dbt test --store_failures with a custom schema defined. When using the custom get_custom_schema.sql file and the macro code:

-- put this in macros/get_custom_schema.sql

{% macro generate_schema_name(custom_schema_name, node) -%}
    {{ generate_schema_name_for_env(custom_schema_name, node) }}
{%- endmacro %}

which is provided on this help page: https://docs.getdbt.com/docs/building-a-dbt-project/building-models/using-custom-schemas

The implementation will appropriately write the test results to the same schema as the data as desired. However, if you try to run the dbt test command more than once it will fail all tests indicating the test table already exists on subsequent runs.

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Add the get_custom_schema.sql macro from the documentation to the macros folder.
Run dbt test --store_failures against any defined test
Run dbt test --store_failures again

### Expected behavior

I would expect the tables created in the initial run of dbt test --store_failures to be dropped and repopulated.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

Log of Run one:

09:20:47 | Concurrency: 1 threads (target='dev')

09:20:47 |

09:20:47 | 1 of 11 START test not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH...... [RUN]

09:20:51 | 1 of 11 PASS not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH............ [PASS in 3.49s]

09:20:51 | 2 of 11 START test not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE........... [RUN]

09:20:54 | 2 of 11 FAIL 1 not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE............... [FAIL 1 in 3.48s]

09:20:54 | 3 of 11 START test not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR.... [RUN]

09:20:58 | 3 of 11 PASS not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR.......... [PASS in 3.44s]

09:20:58 | 4 of 11 START test not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK.......... [RUN]

09:21:01 | 4 of 11 PASS not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK................ [PASS in 3.36s]

09:21:01 | 5 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH.... [RUN]

09:21:09 | 5 of 11 PASS not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH.......... [PASS in 8.13s]

09:21:09 | 6 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE......... [RUN]

09:21:12 | 6 of 11 FAIL 1 not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE............. [FAIL 1 in 3.42s]

09:21:12 | 7 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR.. [RUN]

09:21:16 | 7 of 11 PASS not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR........ [PASS in 3.41s]

09:21:16 | 8 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK........ [RUN]

09:21:19 | 8 of 11 PASS not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK.............. [PASS in 3.39s]

09:21:19 | 9 of 11 START test not_null_claims_rx_paid_Claim_Plan_liability_amt.. [RUN]

09:21:22 | 9 of 11 ERROR not_null_claims_rx_paid_Claim_Plan_liability_amt....... [ERROR in 3.12s]

09:21:22 | 10 of 11 START test unique_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [RUN]

09:21:26 | 10 of 11 PASS unique_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [PASS in 3.50s]

09:21:26 | 11 of 11 START test unique_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [RUN]

09:21:29 | 11 of 11 PASS unique_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [PASS in 3.51s]

09:21:29 |

09:21:29 | Finished running 11 tests in 49.41s.

Log of subsequent run:
09:23:13 | Concurrency: 1 threads (target='dev')

09:23:13 |

09:23:13 | 1 of 11 START test not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH...... [RUN]

09:23:16 | 1 of 11 ERROR not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH........... [ERROR in 3.00s]

09:23:16 | 2 of 11 START test not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE........... [RUN]

09:23:19 | 2 of 11 ERROR not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE................ [ERROR in 2.94s]

09:23:19 | 3 of 11 START test not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR.... [RUN]

09:23:22 | 3 of 11 ERROR not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR......... [ERROR in 3.29s]

09:23:22 | 4 of 11 START test not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK.......... [RUN]

09:23:25 | 4 of 11 ERROR not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK............... [ERROR in 2.94s]

09:23:25 | 5 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH.... [RUN]

09:23:29 | 5 of 11 ERROR not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH......... [ERROR in 3.95s]

09:23:29 | 6 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE......... [RUN]

09:23:34 | 6 of 11 ERROR not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE.............. [ERROR in 4.52s]

09:23:34 | 7 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR.. [RUN]

09:23:37 | 7 of 11 ERROR not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR....... [ERROR in 3.57s]

09:23:37 | 8 of 11 START test not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK........ [RUN]

09:23:42 | 8 of 11 ERROR not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK............. [ERROR in 4.46s]

09:23:42 | 9 of 11 START test not_null_claims_rx_paid_Claim_Plan_liability_amt.. [RUN]

09:23:45 | 9 of 11 ERROR not_null_claims_rx_paid_Claim_Plan_liability_amt....... [ERROR in 3.60s]

09:23:45 | 10 of 11 START test unique_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [RUN]

09:23:48 | 10 of 11 ERROR unique_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [ERROR in 2.93s]

09:23:48 | 11 of 11 START test unique_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [RUN]

09:23:52 | 11 of 11 ERROR unique_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ [ERROR in 3.23s]

09:23:52 |

09:23:52 | Finished running 11 tests in 48.50s.

Completed with 11 errors and 0 warnings:

 

Database Error in test not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495251] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_172_ELIG_YEAR_MONTH' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495252] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_172_MEMBER_AGE' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495253] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495254] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_172_PLAN_DIM_CK' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495255] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_FINAL_ELIG_YEAR_MONTH' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495256] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_AGE' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495257] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495259] [Teradata Database] [Error 3803] Table 'not_null_ELIG_YEAR_MONTH_FINAL_PLAN_DIM_CK' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test not_null_claims_rx_paid_Claim_Plan_liability_amt (models/model_schema.yml)

  [Version 17.0.0.8] [Session 1495260] [Teradata Database] [Error 3523] An owner referenced by user does not have SELECT WITH GRANT OPTION access to CORE_ANALYTICS_AV.CLAIMS_RX.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test unique_ELIG_YEAR_MONTH_172_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495265] [Teradata Database] [Error 3803] Table 'unique_ELIG_YEAR_MONTH_172_dddd28b4a26f859de0f3261a5b0b3488' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Database Error in test unique_ELIG_YEAR_MONTH_FINAL_MEMBER_SYSTEM_NBR_CAST_ELIG_YEAR_MONTH_AS_VARCHAR_6_CAST_PLAN_DIM_CK_AS_VARCHAR_3_ (models/usecase2/usecase2_tests.yml)

  [Version 17.0.0.8] [Session 1495266] [Teradata Database] [Error 3803] Table 'unique_ELIG_YEAR_MONTH_FINAL_7b47eb37b96a36afef5eeb1aed1d0f6d' already exists.

   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1139

   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1155

   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1218

   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:1807

   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:640

   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:499

   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122

   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2091

   at database/sql.ctxDriverQuery ctxutil.go:48

   at database/sql.(*DB).queryDC.func1 sql.go:1579

   at database/sql.withLock sql.go:3204

   at database/sql.(*DB).queryDC sql.go:1574

   at database/sql.(*Conn).QueryContext sql.go:1823

   at main.goCreateRows goside.go:652

   at main._cgoexpwrap_77d8608a8960_goCreateRows _cgo_gotypes.go:363

   at runtime.cgocallbackg1 cgocall.go:332

   at runtime.cgocallbackg cgocall.go:207

   at runtime.cgocallback_gofunc asm_amd64.s:793

   at runtime.goexit asm_amd64.s:1373

 

Done. PASS=0 WARN=0 ERROR=11 SKIP=0 TOTAL=11
**The output of `dbt --version`:**
```
installed version: 1.0.1
latest version 1.0.4

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
-teradata 1.0.1.1.
```

**The operating SYSTEM you're using:**
Ubuntu  18.04.5 LTS
**The output of `python --version`:**
Python 3.9.11
### Additional context
This behavior works as expected through the dbt cloud interface.

**Comment by septimit** [comment] 2023-10-19 08:58
This does not seems related to the teradata plugin and cannot be reproduced using later versions of dbt and the plugin
I have failed to reproduce the error using this setup:
> $ python --version
> Python 3.9.18

> $ dbt -v
> Core:
>   - installed: 1.6.2
>   - latest:    1.6.6 - Update available!
> 
>   Your version of dbt-core is out of date!
>   You can find instructions for upgrading here:
>   https://docs.getdbt.com/docs/installation
> 
> Plugins:
>   - teradata: 1.6.0 - Up to date!

Please check again if you can reproduce.

**Comment by VarunSharma15** [comment] 2023-11-21 06:31
Hi @DEVi1wing, 
Please let us know if issue still persists by creating a new issue.
I am closing this issue as we are not able to reproduce it.
Thanks @septimit

**Closed by VarunSharma15** 2023-11-21 06:31 UTC
Labels: bug
